/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

#include<stdio.h>

char findTheDifference(char* s, char* t) 
{
    char ret = '\0';

    while(*s != '\0')
    {
        ret ^= *s;
        s++;
    }

    while(*t != '\0')
    {
        ret ^= *t;
        t++;
    }

    return ret;
}

int main()
{
    int str1 = {"abcd"};
    int str2 = {"abcde"};

    printf("%c\n",findTheDifference(str1,str2));
    return 0;
}